.TH ASCII2MSEED 1 2009/11/20
.SH NAME
ASCII time series to Mini-SEED converter

.SH SYNOPSIS
.nf
ascii2mseed [options] file1 [file2 file3 ...]

.fi
.SH DESCRIPTION
\fBascii2mseed\fP converts simple ASCII time series data to Mini-SEED
format.  If an input file name is prefixed with an '@' character the
file is assumed to contain a list of input data files, see \fILIST
FILES\fP below.  All output Mini-SEED records will be written to a
specified output file.

.SH OPTIONS

.IP "-V         "
Print program version and exit.

.IP "-h         "
Print program usage and exit.

.IP "-v         "
Be more verbose.  This flag can be used multiple times ("-v -v" or
"-vv") for more verbosity.

.IP "-S         "
Include SEED blockette 100 in each output record with the sample rate
in floating point format.  The basic format for storing sample rates
in SEED data records is a rational approximation
(numerator/denominator).  Precision will be lost if a given sample
rate cannot be well approximated.  This option should be used in those
cases.

.IP "-r \fIbytes\fP"
Specify the Mini-SEED record length in \fIbytes\fP, default is 4096.

.IP "-e \fIencoding\fP"
Specify the Mini-SEED data encoding format, default is 11 (Steim-2
compression) for integer data and 4 for floats (stored uncompressed).
Other supported encoding formats include 10 (Steim-1 compression), 1
(16-bit integers) and 3 (uncompressed 32-bit integers).

.IP "-b \fIbyteorder\fP"
Specify the Mini-SEED byte order, default is 1 (big-endian or most
significant byte first).  The other option is 0 (little-endian or
least significant byte first).  It is highly recommended to always
create big-endian SEED.

.IP "-o \fIoutfile\fP"
Write all Mini-SEED records to \fIoutfile\fP, if \fIoutfile\fP is a
single dash (-) then all Mini-SEED output will go to stdout.  All
diagnostic output from the program is written to stderr and should
never get mixed with data going to stdout.

.SH LIST FILES
If an input file is prefixed with an '@' character the file is assumed
to contain a list of file for input.  Multiple list files can be
combined with multiple input files on the command line.  The last,
space separated field on each line is assumed to be the file name to
be read.

An example of a simple text list:

.nf
tspair.ascii
slist.ascii
.fi

.SH AUTHOR
.nf
Chad Trabant
IRIS Data Management Center
.fi
